### ISSUE TITLE
"Unable to load DLL Microsoft.DiaSymReader.Native.amd64.dll" on net472 if any referenced package targets netstandard2.0

### ISSUE THREAD

**Issue by jnm2** [dotnet/symreader-converter#151]
@tmat I'm in a weird situation. Microsoft.DiaSymReader.Converter works fine unless I add an unrelated package reference (in this case, ShellProgressBar) which has a netstandard2.0 target. Then it starts doing this:

> System.DllNotFoundException: 'Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

If I roll back to ShellProgressBar 4.0.0, Microsoft.DiaSymReader.Converter resumes working. The only thing I can see is that 4.0.0 only has a netstandard1.3 target and 4.2.0 also has a netstandard2.0 target, but why would adding a package reference with netstandard2.0 to a net472 project cause Microsoft.DiaSymReader.Converter to stop finding Microsoft.DiaSymReader.Native.amd64.dll?
I verified that it's the netstandard2.0 target that's causing it by renaming the folder `%userprofile%\.nuget\packages\shellprogressbar\4.2.0\lib\netstandard2.0` temporarily and seeing that Microsoft.DiaSymReader.Converter starts working again.

(I want to upgrade ShellProgressBar because 4.0.0 is acting weird and buggy.)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="2.6.1" />
    <PackageReference Include="Microsoft.DiaSymReader.Converter" Version="1.1.0-beta1-62318-01" />
    <PackageReference Include="NuGet.PackageManagement" Version="4.5.0" />
    <PackageReference Include="ShellProgressBar" Version="4.0.0" />
    <PackageReference Include="System.Reflection.Metadata" Version="1.5.0" />
  </ItemGroup>

</Project>
```

**Comment by jnm2** [comment]
`Microsoft.DiaSymReader.Native.amd64.dll` stops showing up in the net472 build output as soon as any referenced package is using a netstandard2.0.

**Comment by jnm2** [comment]
Without a netstandard2.0 package reference, `Assembly = C:\Program Files\dotnet\sdk\2.1.504\Sdks\Microsoft.NET.Sdk\targets\..\tools\net46/Microsoft.NET.Build.Tasks.dll` returns `Microsoft.DiaSymReader.Native.amd64.dll` and there are a lot of hits:

![image](https://user-images.githubusercontent.com/8040367/54774897-2613c500-4be3-11e9-8ac6-1cdef1aa0732.png)

With a netstandard2.0 package reference, nothing shows up at all:

![image](https://user-images.githubusercontent.com/8040367/54774927-32981d80-4be3-11e9-91e3-58be1b733fba.png)

**Comment by jnm2** [comment]
It's in the project.assets.json in both situations.

**Comment by jnm2** [comment]
Very interesting! If I rename *either* the folder `%userprofile%\.nuget\packages\shellprogressbar\4.2.0\lib\netstandard2.0` *or* the folder `%userprofile%\.nuget\packages\shellprogressbar\4.2.0\lib\netstandard1.3`, `Microsoft.DiaSymReader.Native.amd64.dll` shows up again.

So it's not netstandard2.0 that triggers the bug, it's package references that multitarget certain versions?

**Comment by jnm2** [comment]
My workaround for now is to add this to the csproj:

```xml
  <ItemGroup>
    <ReferenceCopyLocalPaths Include="C:\Users\jmusser\.nuget\packages\microsoft.diasymreader.native\1.7.0\runtimes\win-x64\native\Microsoft.DiaSymReader.Native.amd64.dll "/>
  </ItemGroup>
```

**Comment by jnm2** [comment]
Looks like this issue belongs at https://github.com/dotnet/sdk/issues/3031 and it's getting taken care of there.

**Comment by Vinugd** [comment]
I faced the same issue. Even after installing the nuget package of DiaSymReader it gave me the build error. So I did this to the csproj file
Edit the csproj file (using a notepad preferably) and you should find the xml tag <PropertyGroup>
Under this there is one property called <Deterministic>true</Deterministic>
Comment this line. Save, reload and build. The error is gone!  ()

**Comment by Vinugd** [comment]
I faced the same issue. Even after installing the nuget package of DiaSymReader it gave me the build error. So I did this to the csproj file
Edit the csproj file (using a notepad preferably) and you should find the xml tag `<PropertyGroup>`
Under this there is one property called `<Deterministic>true</Deterministic>`
Comment this line. Save, reload and build. The error is gone! `(<!--<Deterministic>true</Deterministic>-->)`
